Add AD assay metadata template keys and values
Sage-Bionetworks/synapseAnnotations pull request #823
Opened 2021-06-03 22:26 UTC by avanlinden

This PR adds terms for 6 new AD-related keys for MRI, PET, and autorad templates.

2021-06-03 23:18 UTC, Aryllen requested changes
I noticed that all the strings here are limited to 50 characters. This is handy because it could decrease problems with file views, if any of these end up annotations. I don't _think_ 50 characters is too limiting so it should be fine.

I think `filename` would be better in a different module, though. It's not exactly a manifestKey, but it is a file-related key and manifests are file-related. What do you think about putting this in the manifestKey folder/module?

2021-06-03 23:38 UTC, avanlinden commented
I just used the term templates for free strings -- I can change the max string length if needed. I _think_ 50 should be enough for all of them, though? Unless there's an upsettingly long contrast agent or something. 

I moved filename to the manifest module.

2021-06-04 16:48 UTC, Aryllen commented on terms/manifestKeys/filename.json
> +  "$id": "sage.annotations-manifest.filename-0.0.1",
```suggestion
  "$id": "sage.annotations-manifestKeys.filename-0.0.1",
```
Just one minor fix.

2021-06-04 16:55 UTC, avanlinden commented on terms/manifestKeys/filename.json
> +  "$id": "sage.annotations-manifest.filename-0.0.1",
Ayyy good catch.

2021-06-04 16:56 UTC, Aryllen approved these changes
Looks good to me! The string lengths can be changed in the future, if needed.

2021-06-04 16:56 UTC, merged