Add scirnaSeq to Assays
Sage-Bionetworks/synapseAnnotations pull request #825
Opened 2021-06-07 20:45 UTC by pitviper6

2021-06-07 21:03 UTC, kelshmo commented on terms/experimentalData/assay.json
> +        }.
```suggestion
        },
```

2021-06-07 21:05 UTC, kelshmo requested changes
The term and description looks good. There is a typo in the format, I have proposed the change from . to ,. I also believe the id # needs to be [incremented here](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/b9ea3238206da5e677994686e0396605966761df/terms/experimentalData/assay.json#L3). Can you confirm this @avanlinden ?

2021-06-07 21:12 UTC, avanlinden commented
@kelshmo @pitviper6 Correct, the version id should be incremented as well!

2021-06-07 21:23 UTC, pitviper6 commented
Thanks! By incremented, do I add an increment of one to the number (aka,
0.0.12 to 0.0.13?

On Mon, Jun 7, 2021 at 4:12 PM Abby Vander Linden ***@***.***>
wrote:

> @kelshmo <https://github.com/kelshmo> @pitviper6
> <https://github.com/pitviper6> Correct, the version id should be
> incremented as well!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Sage-Bionetworks/synapseAnnotations/pull/825#issuecomment-856260309>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADY2S7VQQPQ5PWSVPLRUHJTTRUY3JANCNFSM46IOGIYQ>
> .
>

2021-06-07 22:04 UTC, avanlinden commented
> Thanks! By incremented, do I add an increment of one to the number (aka, 0.0.12 to 0.0.13?

Yep!

2021-06-15 16:45 UTC, Aryllen approved these changes
I incremented the assay version.

2021-06-15 16:45 UTC, Aryllen commented
@kelshmo, will you please check over and approve?

2021-06-21 16:56 UTC, kelshmo approved these changes

2021-06-21 16:56 UTC, merged